### ISSUE TITLE
Simple example in README.md doesn't work

### ISSUE THREAD

**Issue by jabl** [sheganinans/stockfighter#1]
I'm a bit of a Rust n00b, but anyway, here goes:

   Compiling level2_chock_a_block v0.1.0 (file:///Users/janne/Documents/stockfighter/level2_chock_a_block)
src/main.rs:7:22: 7:69 error: the trait bound `stockfighter::HyperResult<stockfighter::VenueHeartbeat>: std::fmt::Debug` is not satisfied [E0277]
src/main.rs:7     println!("{:#?}",sf.venue_heartbeat(Venue("TESTEX".to_string())));
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/main.rs:7:22: 7:69 note: in this expansion of format_args!
src/main.rs:7:22: 7:69 note: in this expansion of print! (defined in <std macros>)
src/main.rs:7:22: 7:69 note: in this expansion of println! (defined in <std macros>)
src/main.rs:7:22: 7:69 help: run `rustc --explain E0277` to see a detailed explanation
src/main.rs:7:22: 7:69 note: `stockfighter::HyperResult<stockfighter::VenueHeartbeat>` cannot be formatted using `:?`; if it is defined in your crate, add `#[derive(Debug)]` or manually implement it
src/main.rs:7:22: 7:69 note: required by `std::fmt::Debug::fmt`
error: aborting due to previous error
error: Could not compile `level2_chock_a_block`.

This is with the compiler version

rustc 1.10.0-nightly (4ec5ce5e4 2016-05-12)

Toolchain (installed with rustup): nightly-x86_64-apple-darwin

**Comment by sheganinans** [comment]
Sorry this passed me by so long, it seems the Debug instance for HyperResult disappeared at some point. I slapped it back on, it should work now, try installing version 0.2.1.
